server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: netservice-boot
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netservice_boot?serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mappings/**/*Mapper.xml
  type-aliases-package: com.htphy.wx.module.*.model

logging.level:
  root: info
  com.htphy.wx: debug

